# Generated by Django 3.0.5 on 2022-03-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherextra',
            old_name='salary',
            new_name='salario',
        ),
    ]
