# Generated by Django 3.0.5 on 2022-03-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20220325_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherextra',
            old_name='joindate',
            new_name='dt_contrato',
        ),
    ]
