# Generated by Django 3.0.5 on 2022-03-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20220325_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('1C', '1C'), ('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('Cursinho', 'Cursinho')], default='1A', max_length=10),
        ),
    ]
